        # Navigate to your project folder
        cd QB_SHELL_PROJECT_2
        
        # Pull the newest code from GitHub
        git pull origin main
        
        # Make sure the script is executable and run it
        git config --global --add safe.directory /home/ubuntu/qualibytes
        chmod +x deploy.sh
        ./deploy.sh https://github.com/rahullikhar/QB_SHELL_PROJECT_2.git
